camel:
  springboot:
    name: camel-reactive-demo
    
management:
  endpoint:
    camelroutes:
      enabled: true
      read-only: true
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,camelroutes
